baseURL = 'http://wysockipoolservices.com/'
languageCode = 'en-us'
title = 'Wysocki Pool'
theme = 'hugo-arcana'
copyright = 'Â© Wysocki Pool. All rights reserved'

defaultContentLanguage = 'en'

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Services"
    url = "/services"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3

[params]
    description = 'Wysocki Pool - Professional pool services'
    show_post_dates = false

    [params.footer]
        [[params.footer.links]]
            header = "Contact"
        [[params.footer.links.links]]
            title = "Phone: 734.278.8954"
            url = "tel:7342788954"
        [[params.footer.links.links]]
            title = "wysockipoolservices@gmail.com"
            url = "mailto:wysockipoolservices@gmail.com"

        [[params.footer.links]]
            header = "Services"
        [[params.footer.links.links]]
            title = "Pool Opening"
            url = "/services#pool-opening"
        [[params.footer.links.links]]
            title = "Pool Closing"
            url = "/services#pool-closing"
        [[params.footer.links.links]]
            title = "Weekly Chemical Service"
            url = "/services#weekly-chemical-service"
        [[params.footer.links.links]]
            title = "Sand Filter Maintenance"
            url = "/services#sand-filter-maintenance%2freplacement"
        [[params.footer.links.links]]
            title = "Pvc Repair/Equipment Remodel"
            url = "/services#pvc-repair-equipment-remodel"

        [params.footer.contact_form]
            enabled = false
            header = "Get In Touch"
            action = ""
