baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Wysocki Pool'
theme = 'hugo-arcana'
copyright = 'Â© Wysocki Pool. All rights reserved'

defaultContentLanguage = 'en'

[params]
    description = 'Wysocki Pool - Professional pool services'
    show_post_dates = false

    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "#"
    [[params.social]]
        title = "Instagram"
        icon = "fa-instagram"
        url = "#"

    [params.footer]
        [[params.footer.links]]
            header = "Services"
        [[params.footer.links.links]]
            title = "Pool Maintenance"
            url = "#"
        [[params.footer.links.links]]
            title = "Pool Cleaning"
            url = "#"
        [[params.footer.links.links]]
            title = "Pool Repair"
            url = "#"

        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = ""
