baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'Wysocki Pool'
theme = 'hugo-arcana'
copyright = 'Â© Wysocki Pool. All rights reserved'

defaultContentLanguage = 'en'

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Services"
    url = "/services"
    weight = 2

[params]
    description = 'Wysocki Pool - Professional pool services'
    show_post_dates = false

    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "#"
    [[params.social]]
        title = "Instagram"
        icon = "fa-instagram"
        url = "#"

    [params.footer]
        [[params.footer.links]]
            header = "Services"
        [[params.footer.links.links]]
            title = "Pool Opening"
            url = "/services#pool-opening"
        [[params.footer.links.links]]
            title = "Pool Closing"
            url = "/services#pool-closing"
        [[params.footer.links.links]]
            title = "Weekly Chemical Service"
            url = "/services#weekly-chemical-service"
        [[params.footer.links.links]]
            title = "Sand Filter Maintenance"
            url = "/services#sand-filter-maintenance-replacement"
        [[params.footer.links.links]]
            title = "Pvc Repair/Equipment Remodel"
            url = "/services#pvc-repair-equipment-remodel"

        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = ""
